[patch] update Docker Image Tag to differentiate DEV and PROD

diff --git a/.github/workflows/react-application.yaml b/.github/workflows/react-application.yaml
--- a/.github/workflows/react-application.yaml
+++ b/.github/workflows/react-application.yaml
@@ -109,12 +109,28 @@ jobs:
           aws-region: ${{ secrets.AWS_REGION }}
           aws-role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
 
+      # Fix Image Tag
+      - name: Compute image tag
+        shell: bash
+        run: |
+          if [[ -z "${{ env.NEW_VERSION }}" ]]; then
+            echo "NEW_VERSION is empty — aborting"
+            exit 1
+          fi
+
+          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+            echo "IMAGE_TAG=${{ env.NEW_VERSION }}" >> $GITHUB_ENV
+          else
+            SHORT_SHA="${GITHUB_SHA::7}"
+            echo "IMAGE_TAG=${{ env.NEW_VERSION }}-dev.${SHORT_SHA}" >> $GITHUB_ENV
+          fi
+
       # Docker build & push
       - name: Build and push Docker image
         uses: musimap/cicd/github-actions/_partials/steps-build-docker@main
         with:
           ecr-repo: ${{ secrets.ECR_REGISTRY }}/${{ github.event.repository.name }}
-          new-version: ${{ env.NEW_VERSION }}
+          new-version: ${{ env.IMAGE_TAG }}
           aws-region: ${{ secrets.AWS_REGION }}
 
       # Update Kustomize overlay
@@ -122,7 +138,7 @@ jobs:
         uses: musimap/cicd/github-actions/_partials/steps-update-kustomize@main
         with:
           overlay-path: ${{ env.OVERLAY_PATH }}
-          new-version: ${{ env.NEW_VERSION }}
+          new-version: ${{ env.IMAGE_TAG }}
 
       # Commit version + kustomize changes
       - name: Commit version & Kustomize
